
package guermann.sample.wssample;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MeminfoService", targetNamespace = "http://wssample.sample.guermann/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MeminfoService {


    /**
     * 
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAvailableMemorySize", targetNamespace = "http://wssample.sample.guermann/", className = "guermann.sample.wssample.GetAvailableMemorySize")
    @ResponseWrapper(localName = "getAvailableMemorySizeResponse", targetNamespace = "http://wssample.sample.guermann/", className = "guermann.sample.wssample.GetAvailableMemorySizeResponse")
    @Action(input = "http://wssample.sample.guermann/MeminfoService/getAvailableMemorySizeRequest", output = "http://wssample.sample.guermann/MeminfoService/getAvailableMemorySizeResponse")
    public long getAvailableMemorySize();

}
