
package guermann.sample.wssample;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MeminfoServiceService", targetNamespace = "http://wssample.sample.guermann/", wsdlLocation = "http://localhost:8080/MeminfoService-1.0-SNAPSHOT/MeminfoService?wsdl")
public class MeminfoServiceService
    extends Service
{

    private final static URL MEMINFOSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MEMINFOSERVICESERVICE_EXCEPTION;
    private final static QName MEMINFOSERVICESERVICE_QNAME = new QName("http://wssample.sample.guermann/", "MeminfoServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/MeminfoService-1.0-SNAPSHOT/MeminfoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEMINFOSERVICESERVICE_WSDL_LOCATION = url;
        MEMINFOSERVICESERVICE_EXCEPTION = e;
    }

    public MeminfoServiceService() {
        super(__getWsdlLocation(), MEMINFOSERVICESERVICE_QNAME);
    }

    public MeminfoServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEMINFOSERVICESERVICE_QNAME, features);
    }

    public MeminfoServiceService(URL wsdlLocation) {
        super(wsdlLocation, MEMINFOSERVICESERVICE_QNAME);
    }

    public MeminfoServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEMINFOSERVICESERVICE_QNAME, features);
    }

    public MeminfoServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MeminfoServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MeminfoService
     */
    @WebEndpoint(name = "MeminfoServicePort")
    public MeminfoService getMeminfoServicePort() {
        return super.getPort(new QName("http://wssample.sample.guermann/", "MeminfoServicePort"), MeminfoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MeminfoService
     */
    @WebEndpoint(name = "MeminfoServicePort")
    public MeminfoService getMeminfoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wssample.sample.guermann/", "MeminfoServicePort"), MeminfoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEMINFOSERVICESERVICE_EXCEPTION!= null) {
            throw MEMINFOSERVICESERVICE_EXCEPTION;
        }
        return MEMINFOSERVICESERVICE_WSDL_LOCATION;
    }

}
